const http=require('http');
const{spawn}=require('child_process');
const fs=require('fs');
const path=require('path');
const PUBLIC_PORT=Number(process.env.PORT)||10000;
const INTERNAL_PORT=PUBLIC_PORT===10001?10002:10001;
const scriptFiles={common:[['shrivi-features.js','shrivi-features.js'],['shrivi-upgrade-suite.js','shrivi-upgrade-suite.js'],['amazon-style-upgrade.js','amazon-style-upgrade.js'],['shrivi-production-upgrade.js','shrivi-production-upgrade.js'],['shrivi-app-init.js','shrivi-app-init.js']],customer:[['shrivi-customer-backend.js','shrivi-customer-backend.js'],['customer-gallery-v2.js','customer-gallery-v2.js'],['customer-cleanup.js','customer-cleanup.js']]};
const all=[...scriptFiles.common,...scriptFiles.customer];
const assets=Object.fromEntries(all.map(([url,file])=>['/'+url,fs.readFileSync(path.join(__dirname,file),'utf8')]));
assets['/customer-premium.css']=fs.readFileSync(path.join(__dirname,'customer-premium.css'),'utf8');
function pageScripts(pathname){if(pathname==='/seller'||pathname==='/seller/')return [];if(pathname==='/shop'||pathname==='/shop/')return [...scriptFiles.common,...scriptFiles.customer];if(pathname==='/'||pathname==='/admin'||pathname==='/admin/')return [...scriptFiles.common];return []}
// Seller API is now one canonical layer. Old seller repair/injection modules are intentionally not preloaded.
const preload=['shrivi-db-upgrades.js','seller-canonical-api.js'];
const preloadArgs=preload.flatMap(file=>['-r',path.join(__dirname,file)]);
const child=spawn(process.execPath,[...preloadArgs,path.join(__dirname,'server.js')],{env:{...process.env,PORT:String(INTERNAL_PORT)},stdio:'inherit'});
child.on('exit',c=>process.exit(c??1));
const server=http.createServer((req,res)=>{const pathname=(req.url||'/').split('?')[0];if(assets[pathname]){const isCss=pathname==='/customer-premium.css';res.writeHead(200,{'content-type':isCss?'text/css; charset=utf-8':'application/javascript; charset=utf-8','cache-control':'no-store'});return res.end(assets[pathname])}const proxyReq=http.request({hostname:'127.0.0.1',port:INTERNAL_PORT,method:req.method,path:req.url,headers:{...req.headers,host:`127.0.0.1:${INTERNAL_PORT}`,'accept-encoding':'identity'},timeout:30000},proxyRes=>{const type=String(proxyRes.headers['content-type']||'').toLowerCase();const scripts=pageScripts(pathname);if(!(req.method==='GET'&&/text\/html/.test(type)&&(scripts.length||pathname==='/shop'||pathname==='/shop/'))){res.writeHead(proxyRes.statusCode||200,proxyRes.headers);return proxyRes.pipe(res)}const chunks=[];proxyRes.on('data',c=>chunks.push(c));proxyRes.on('end',()=>{let html=Buffer.concat(chunks).toString('utf8');html=html.replace(/<script[^>]+(?:shrivi-features|shrivi-upgrade-suite|amazon-style-upgrade|shrivi-production-upgrade|shrivi-customer-backend|shrivi-app-init|seller-pro-listing-ui|seller-gallery-v2|seller-multi-images|seller-multi-select-fix|seller-8-slots|customer-gallery-v2|seller-final-fix|seller-images-router-fix)[^>]*><\/script>/gi,'');const tags=scripts.map(([url])=>`<script src="/${url}?v=38"></script>`).join('\n');const premium=(pathname==='/shop'||pathname==='/shop/')?'<link rel="stylesheet" href="/customer-premium.css?v=1">':'';html=/<\/head>/i.test(html)?html.replace(/<\/head>/i,`${premium}\n</head>`):html;html=/<\/body>/i.test(html)?html.replace(/<\/body>/i,`${tags}\n</body>`):`${html}\n${tags}`;const headers={...proxyRes.headers};delete headers['content-length'];delete headers.etag;delete headers['content-encoding'];headers['content-type']='text/html; charset=utf-8';headers['cache-control']='no-store';res.writeHead(proxyRes.statusCode||200,headers);res.end(html)})});proxyReq.on('timeout',()=>proxyReq.destroy());proxyReq.on('error',()=>{if(!res.headersSent)res.writeHead(502,{'content-type':'text/plain; charset=utf-8'});if(!res.writableEnded)res.end('Shrivi service temporarily unavailable.')});req.pipe(proxyReq)});
server.listen(PUBLIC_PORT,'0.0.0.0',()=>console.log(`Shrivi feature proxy listening on ${PUBLIC_PORT}`));
function shutdown(){server.close(()=>child.kill('SIGTERM'));setTimeout(()=>child.kill('SIGKILL'),5000).unref()}process.on('SIGTERM',shutdown);process.on('SIGINT',shutdown);
